name: fhirlite_demo
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fhirlite:
    path: ../fhirlite
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/
  - assets/images/
  - .env

# dependency_overrides:
#   biometric_storage: ^5.0.0